import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowRight, Eye, EyeOff, LogOut, X } from 'lucide-react';
import Logo from './Logo';
import { api, errorMessage, setCsrfToken } from '../services/api';
export interface User { id:string; name:string; email:string; verified:boolean }
interface Session { user:User|null; csrfToken:string|null }
type Mode='login'|'register'|'forgot'|'reset'|'verify';
export default function AuthGate({children}:{children:(user:User,onAccount:()=>void)=>ReactNode}) {
 const [recovery]=useState(()=>{const fragment=new URLSearchParams(window.location.hash.slice(1));return {token:fragment.get('reset')||fragment.get('verify')||'',mode:(fragment.has('reset')?'reset':fragment.has('verify')?'verify':'login') as Mode};});
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState<Mode>(recovery.mode);
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[show,setShow]=useState(false);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[token,setToken]=useState(recovery.token);
 const [account,setAccount]=useState(false),[privacy,setPrivacy]=useState(false),[confirmDelete,setConfirmDelete]=useState(false);
 const errorRef=useRef<HTMLParagraphElement>(null),accountRef=useRef<HTMLDialogElement>(null),privacyRef=useRef<HTMLDialogElement>(null);
 const applySession=useCallback((session:Session)=>{setUser(session.user);setCsrfToken(session.csrfToken);},[]);
 useEffect(()=>{
  let active=true;
  if(recovery.token)window.history.replaceState(null,'',window.location.pathname+window.location.search);
  void api.get<Session>('/auth/session').then(r=>{if(active)applySession(r.data);}).catch(e=>{if(active)setError(errorMessage(e));}).finally(()=>{if(active)setLoading(false);});
  const expired=()=>{applySession({user:null,csrfToken:null});setAccount(false);setPassword('');setError('Your session has ended. Please sign in again.');};
  const recoveryLink=()=>{const fragment=new URLSearchParams(window.location.hash.slice(1));const reset=fragment.get('reset'),verify=fragment.get('verify');if(reset||verify){setToken(reset||verify||'');setMode(reset?'reset':'verify');setPassword('');setError('');setMessage('');window.history.replaceState(null,'',window.location.pathname+window.location.search);}};
  window.addEventListener('session-expired',expired);
  window.addEventListener('hashchange',recoveryLink);
  return()=>{active=false;window.removeEventListener('session-expired',expired);window.removeEventListener('hashchange',recoveryLink);};
 },[applySession,recovery.token]);
 useEffect(()=>{if(error)errorRef.current?.focus();},[error]);
 useEffect(()=>{if(account)accountRef.current?.showModal();else accountRef.current?.close();},[account]);
 useEffect(()=>{if(privacy)privacyRef.current?.showModal();else privacyRef.current?.close();},[privacy]);
 function changeMode(next:Mode){setMode(next);setError('');setMessage('');setPassword('');setShow(false);}
 async function action(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function submit(){await action(async()=>{
  if(mode==='login'){const {data}=await api.post<Session>('/auth/login',{email,password});applySession(data);setPassword('');}
  if(mode==='register'){const {data}=await api.post('/auth/register',{email,password,name});setMessage(data.message);setPassword('');}
  if(mode==='forgot'){const {data}=await api.post('/auth/forgot-password',{email});setMessage(data.message);}
  if(mode==='verify'){const {data}=await api.post('/auth/verify-email',{token});setToken('');setMode('login');setMessage(data.message);applySession((await api.get<Session>('/auth/session')).data);}
  if(mode==='reset'){const {data}=await api.post('/auth/reset-password',{token,password});setToken('');setPassword('');applySession({user:null,csrfToken:null});setMode('login');setMessage(data.message);}
 });}
 async function logout(all=false){await action(async()=>{await api.post(all?'/auth/logout-all':'/auth/logout');applySession({user:null,csrfToken:null});setAccount(false);setPassword('');});}
 const feedback=<>{error&&<p className="auth-error" role="alert" tabIndex={-1} ref={errorRef}>{error}</p>}{message&&<p className="auth-message" role="status">{message}</p>}</>;
 const privacyDialog=<dialog className="editor-dialog privacy-dialog" ref={privacyRef} aria-labelledby="privacy-title" onCancel={()=>setPrivacy(false)}><div className="dialog-heading"><h2 id="privacy-title">Your notes, your space.</h2><button type="button" className="icon-button" aria-label="Close privacy information" onClick={()=>setPrivacy(false)}><X/></button></div><p>Your email, name and password hash are stored to operate your account. Your notes are private to your account.</p><p>Choosing “Complete & make visual” sends that note’s title, subject and text to OpenAI when AI generation is enabled. Demo mode arranges your text without an AI request. Generated study material can contain mistakes; check important facts against your sources.</p><p>Railway hosts the API and database, Netlify serves this website, and the configured email provider delivers verification and recovery emails. Password safety checks send only a five-character hash prefix to Have I Been Pwned.</p><p>You can export notes or delete your account in Account settings. Account deletion removes active records; any infrastructure backups expire under the hosting provider’s configured retention. Security event records are retained for up to 90 days with account references removed on deletion. Sessions expire after seven days or 24 hours of inactivity.</p><p>We use an essential sign-in cookie. This app does not add analytics or advertising trackers.</p></dialog>;
 if(loading)return <main className="auth-page"><p role="status">Opening your study space…</p></main>;
 if(user?.verified&&mode!=='reset'&&mode!=='verify')return <>{children(user,()=>{setError('');setMessage('');setConfirmDelete(false);setPassword('');setAccount(true);})}<dialog ref={accountRef} className="editor-dialog account-dialog" aria-labelledby="account-title" onCancel={e=>{if(busy)e.preventDefault();else setAccount(false);}}><div className="dialog-heading"><div><div className="eyebrow">YOUR STUDY SPACE</div><h2 id="account-title">Account settings</h2></div><button className="icon-button" aria-label="Close account settings" disabled={busy} onClick={()=>setAccount(false)}><X/></button></div>{feedback}<p>{user.name}<br/><span className="account-email">{user.email}</span></p><div className="account-actions"><a className="secondary" href={`${api.defaults.baseURL}/auth/export`} download>Export my notes</a><button className="secondary" disabled={busy} onClick={()=>void logout()}>Sign out<LogOut size={18}/></button><button className="secondary" disabled={busy} onClick={()=>void logout(true)}>Sign out on every device</button><button className="secondary" onClick={()=>setPrivacy(true)}>Privacy information</button></div><hr/><p>To change your password, sign out and choose “Forgot password?”. Resetting it also signs out every device.</p>{confirmDelete?<form onSubmit={e=>{e.preventDefault();void action(async()=>{await api.delete('/auth/account',{data:{password}});applySession({user:null,csrfToken:null});setAccount(false);setPassword('');setMessage('Your account and notes have been deleted.');});}}><h3>Delete your account and all notes?</h3><p>This cannot be undone. Export anything you want to keep first.</p><label>Confirm your current password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="account-actions"><button className="danger" disabled={busy}>{busy?'Deleting…':'Permanently delete account'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>{setConfirmDelete(false);setPassword('');}}>Keep my account</button></div></form>:<button className="danger-outline" onClick={()=>setConfirmDelete(true)}>Delete account…</button>}</dialog>{privacyDialog}</>;
 if(user&&!user.verified&&mode!=='reset'&&mode!=='verify')return <main className="auth-page"><section className="auth-card"><Logo/><div className="eyebrow">ONE SMALL STEP</div><h1>Check your inbox.</h1><p>Verify {user.email} to open your private notebook. Your verification link expires after 24 hours.</p>{feedback}<div className="account-actions"><button className="primary" disabled={busy} onClick={()=>void action(async()=>{const {data}=await api.post('/auth/resend-verification');setMessage(data.message);})}>Resend verification</button><button className="secondary" disabled={busy} onClick={()=>void action(async()=>{applySession((await api.get<Session>('/auth/session')).data);})}>I’ve verified my email</button><button className="secondary" disabled={busy} onClick={()=>void logout()}>Sign out</button></div></section></main>;
 const headings={login:'A little room to think.',register:'Your next idea starts here.',forgot:'Let’s get you back in.',reset:'Choose a new password.',verify:'A notebook of your own.'};
 return <main className="auth-page"><section className="auth-intro" aria-label="Welcome to LiiiGHTNOTES"><Logo/><div><div className="eyebrow">CAPTURE · CONNECT · UNDERSTAND</div><h2>Follow a thought.<br/>Find a little light.</h2><p>A quiet place for your notes, questions and discoveries. Turn what you’re learning into a study page worth coming back to.</p></div><p className="auth-footnote">A little curiosity goes a long way.</p></section><section className="auth-card"><div className="eyebrow">{mode==='register'?'CREATE YOUR STUDY SPACE':mode==='login'?'WELCOME BACK':'YOUR ACCOUNT'}</div><h1>{headings[mode]}</h1>{feedback}<form onSubmit={e=>{e.preventDefault();void submit();}} aria-busy={busy}>
 {mode==='register'&&<label>Your name<input autoComplete="name" required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>}
 {['login','register','forgot'].includes(mode)&&<label>Email address<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label>}
 {['login','register','reset'].includes(mode)&&<div className="auth-field"><label htmlFor="auth-password">Password</label><div className="password-input"><input id="auth-password" type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} aria-describedby={mode!=='login'?'password-help':undefined} required minLength={mode==='login'?1:15} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="icon-button" aria-label={show?'Hide password':'Show password'} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>{mode!=='login'&&<small id="password-help">Use 15–128 characters. A unique passphrase works well. Password managers and pasting are welcome.</small>}</div>}
 {mode==='verify'&&<p>Confirm your email to open your private notebook.</p>}
 <button className="primary auth-submit" disabled={busy}>{busy?'Please wait…':({login:'Sign in',register:'Create account',forgot:'Send reset link',reset:'Save new password',verify:'Verify my email'}[mode])}<ArrowRight size={18}/></button>
 </form><div className="auth-links">{mode==='login'?<><button onClick={()=>changeMode('forgot')}>Forgot password?</button><p>New here? <button onClick={()=>changeMode('register')}>Create an account</button></p></>:<button onClick={()=>changeMode('login')}>Back to sign in</button>}<button onClick={()=>setPrivacy(true)}>How we look after your data</button></div></section>{privacyDialog}</main>;
}
