import { useEffect, useRef, useState } from 'react';
import { X, ArrowUpRight } from 'lucide-react';
import type { NoteInput, StudyNote } from '../types/notes';
export default function NoteEditor({ note,busy,error,onSave,onClose }: { note:StudyNote|null;busy:boolean;error:string;onSave:(input:NoteInput,id?:string)=>Promise<boolean>;onClose:()=>void }) {
 const [title,setTitle]=useState(note?.title||''), [content,setContent]=useState(note?.content||''), [subject,setSubject]=useState(note?.subject||'General');
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ const el=dialog.current; el?.showModal(); el?.querySelector('input')?.focus(); return ()=>el?.close(); },[]);
 return <dialog ref={dialog} className="editor-dialog" aria-labelledby="editor-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><form onSubmit={async e=>{e.preventDefault();if(await onSave({title,content,subject},note?.id))onClose();}}><div className="dialog-heading"><div><div className="eyebrow">A THOUGHT WORTH KEEPING</div><h2 id="editor-title">{note?'Edit your note':'Capture a thought.'}</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={busy} aria-label="Close editor"><X/></button></div>{error&&<p role="alert" className="error-banner">{error}</p>}<label>Give it a title<input autoFocus required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What are you thinking about?"/></label><label>Subject<input required maxLength={60} value={subject} onChange={e=>setSubject(e.target.value)} list="subjects"/><datalist id="subjects"><option>Ancient history</option><option>Biology</option><option>Literature</option><option>General</option></datalist></label><label>Your study notes<textarea required maxLength={20000} rows={9} value={content} onChange={e=>setContent(e.target.value)} placeholder="Collect the facts, questions and connections. This is your space to think."/></label><div className="editor-footer"><small aria-live="polite">{content.length.toLocaleString()} / 20,000<br/>{note?'Saving returns this note to in progress.':'Tick the note when you’re ready to make it visual.'}</small><button className="primary" disabled={busy||!title.trim()||!content.trim()||!subject.trim()}>{busy?'Saving…':'Save note'}<ArrowUpRight size={18}/></button></div></form></dialog>;
}
