import { useState } from 'react';
import { Pencil, Printer, FileText, Sparkles, Trash2, LoaderCircle } from 'lucide-react';
import type { StudyNote } from '../types/notes';
import VisualNote from './VisualNote';
export default function Tray({note,busy,onEdit,onComplete,onDelete}:{note:StudyNote;busy:boolean;onEdit:()=>void;onComplete:()=>void;onDelete:()=>void}) {
 const [tab,setTab]=useState<'visual'|'original'>('visual');
 const [confirmDelete,setConfirmDelete]=useState(false);
 const active=['queued','processing'].includes(note.status);
 return <section className="tray" aria-label="Selected study note"><div className="tray-toolbar"><div className="view-tabs"><button className={tab==='visual'?'active':''} aria-pressed={tab==='visual'} onClick={()=>setTab('visual')}><Sparkles size={15}/>Visual note</button><button className={tab==='original'?'active':''} aria-pressed={tab==='original'} onClick={()=>setTab('original')}><FileText size={15}/>Original</button></div><div className="tray-actions"><button className="icon-button" aria-label="Edit note" title="Edit note" disabled={busy||active} onClick={onEdit}><Pencil size={17}/></button><button className="icon-button" aria-label="Print visual note" title="Print / save PDF" disabled={!note.visual||tab!=='visual'} onClick={()=>window.print()}><Printer size={17}/></button><button className="icon-button" aria-label="Delete note" title="Delete note" disabled={busy||active} onClick={()=>setConfirmDelete(true)}><Trash2 size={17}/></button></div></div>{confirmDelete&&<div className="delete-confirm" role="alert"><span>Delete “{note.title}”?</span><button disabled={busy} onClick={onDelete}>Delete</button><button onClick={()=>setConfirmDelete(false)}>Keep note</button></div>}<div className="tray-canvas">{tab==='original'?<article className="original-sheet"><div className="eyebrow">{note.subject}</div><h2>{note.title}</h2><p>{note.content}</p><button className="secondary" onClick={onEdit} disabled={active||busy}><Pencil size={16}/>Edit original</button></article>:note.visual?<VisualNote spec={note.visual}/>:<div className="generation-empty" role={note.status==='failed'?'alert':'status'} aria-live="polite">{active?<LoaderCircle className="spin" size={38}/>:<Sparkles size={38}/>}<h2>{active?(note.status==='queued'?'Your note is in the queue.':'Your visual note is taking shape.'):note.status==='failed'?'Let’s give that another try.':'Every great idea starts somewhere.'}</h2><p>{active?'Your note is saved. You can keep studying while its visual note takes shape.':note.error||'When your study notes are ready, complete the note and we’ll turn them into a visual study sheet.'}</p>{!active&&<button className="primary" onClick={onComplete} disabled={busy}>{note.status==='failed'?'Retry generation':'Complete & make visual'}<Sparkles size={17}/></button>}</div>}</div></section>;
}
